export const greenman = {
  0: '#e8f6ee',
  1: '#d1edde',
  2: '#a8debe',
  3: '#7bcd9b',
  4: '#52bd7b',
  5: '#2fb160',
  6: '#0e9a47',
  7: '#007d38',
  8: '#006e30',
  9: '#00622a',
} as const;

export const semantic = {
  surface: '#ffffff',
  surfaceMuted: greenman[0],
  surfaceSunken: '#f7f8f6',
  surfaceInverse: '#0f1a12',
  border: '#ececec',
  borderStrong: '#d5d9d5',
  ink: '#0f1a12',
  inkDim: '#5b6360',
  inkMuted: '#9aa09b',
  inkInverse: '#ffffff',
  accent: greenman[7],
  accentMuted: greenman[1],
  accentHover: greenman[8],
  success: '#1b8e3f',
  warning: '#c78412',
  danger: '#c0392b',
  info: '#2b6cb0',
  overlay: 'rgba(15, 26, 18, 0.5)',
} as const;

export const colors = {
  primary: greenman[6],
  primaryDark: greenman[7],
  background: semantic.surface,
  surface: semantic.surface,
  border: semantic.border,
  muted: '#6b7280',
  ink: semantic.ink,
  inkDim: semantic.inkDim,
  danger: semantic.danger,
  warn: semantic.warning,
  success: semantic.success,
} as const;
