/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        greenman: {
          0: '#e8f6ee',
          1: '#d1edde',
          2: '#a8debe',
          3: '#7bcd9b',
          4: '#52bd7b',
          5: '#2fb160',
          6: '#0e9a47',
          7: '#007d38',
          8: '#006e30',
          9: '#00622a',
        },
        background: '#ffffff',
        surface: '#ffffff',
        'surface-muted': '#e8f6ee',
        'surface-sunken': '#f7f8f6',
        'surface-inverse': '#0f1a12',
        border: '#ececec',
        'border-strong': '#d5d9d5',
        muted: '#6b7280',
        ink: '#0f1a12',
        'ink-dim': '#5b6360',
        'ink-muted': '#9aa09b',
        'ink-inverse': '#ffffff',
        accent: '#007d38',
        'accent-muted': '#d1edde',
        success: '#1b8e3f',
        warning: '#c78412',
        danger: '#c0392b',
        info: '#2b6cb0',
      },
      fontFamily: {
        sans: ['Manrope_400Regular', 'System'],
        medium: ['Manrope_500Medium', 'System'],
        semibold: ['Manrope_600SemiBold', 'System'],
        bold: ['Manrope_700Bold', 'System'],
        display: ['Manrope_800ExtraBold', 'System'],
        serif: ['SourceSerif4_400Regular', 'Georgia', 'serif'],
        'serif-italic': ['SourceSerif4_400Regular_Italic', 'Georgia', 'serif'],
      },
      fontSize: {
        meta: ['11px', { lineHeight: '14px' }],
        caption: ['12px', { lineHeight: '16px' }],
        label: ['13px', { lineHeight: '18px' }],
        body: ['15px', { lineHeight: '22px' }],
        'read-body': ['18px', { lineHeight: '30px' }],
        'read-body-lg': ['20px', { lineHeight: '32px' }],
        h3: ['17px', { lineHeight: '22px' }],
        h2: ['20px', { lineHeight: '26px' }],
        h1: ['24px', { lineHeight: '30px' }],
        display: ['30px', { lineHeight: '36px' }],
        'read-h3': ['20px', { lineHeight: '28px' }],
        'read-h2': ['24px', { lineHeight: '32px' }],
        'read-h1': ['30px', { lineHeight: '38px' }],
      },
      borderRadius: {
        sm: '10px',
        md: '14px',
        lg: '20px',
        xl: '28px',
      },
      spacing: {
        'xs4': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '20px',
        'xl': '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '64px',
      },
      boxShadow: {
        soft: '0 1px 2px rgba(15, 26, 18, 0.04), 0 4px 12px rgba(15, 26, 18, 0.06)',
        card: '0 2px 8px rgba(15, 26, 18, 0.06)',
        sheet: '0 8px 24px rgba(15, 26, 18, 0.12)',
        overlay: '0 12px 40px rgba(15, 26, 18, 0.18)',
        pop: '0 8px 24px rgba(15, 26, 18, 0.1)',
      },
    },
  },
  plugins: [],
};
