const CHATWOOT_BASE_URL = process.env.CHATWOOT_BASE_URL || 'https://whaa.ru';
const CHATWOOT_API_INBOX_IDENTIFIER = process.env.CHATWOOT_API_INBOX_IDENTIFIER || '3GkEXyBuMfXWnW7csEqAqahu';
const CHATWOOT_ENABLED = String(process.env.CHATWOOT_ENABLED || 'true').trim().toLowerCase() === 'true';
const CHATWOOT_WEBHOOK_SECRET = process.env.CHATWOOT_WEBHOOK_SECRET || 'SQZ5t6qr53LAsBXzAEA6dVWp';
const CHATWOOT_API_ACCESS_TOKEN = String(process.env.CHATWOOT_API_ACCESS_TOKEN || '').trim();
const CHATWOOT_ACCOUNT_ID = Number.parseInt(String(process.env.CHATWOOT_ACCOUNT_ID || '1').trim(), 10);

module.exports = {
    CHATWOOT_BASE_URL,
    CHATWOOT_API_INBOX_IDENTIFIER,
    CHATWOOT_ENABLED,
    CHATWOOT_WEBHOOK_SECRET,
    CHATWOOT_API_ACCESS_TOKEN,
    CHATWOOT_ACCOUNT_ID: Number.isFinite(CHATWOOT_ACCOUNT_ID) ? CHATWOOT_ACCOUNT_ID : 1
};
