const CHATWOOT_BASE_URL = 'https://whaa.ru';
const CHATWOOT_API_INBOX_IDENTIFIER = '3GkEXyBuMfXWnW7csEqAqahu';
const CHATWOOT_ENABLED = true;
const CHATWOOT_WEBHOOK_SECRET = 'SQZ5t6qr53LAsBXzAEA6dVWp';

module.exports = {
    CHATWOOT_BASE_URL,
    CHATWOOT_API_INBOX_IDENTIFIER,
    CHATWOOT_ENABLED,
    CHATWOOT_WEBHOOK_SECRET
};
